version: '3.8'

services:

  bot:
    image: avnosov/weather-bot:v1
    restart: always
    env_file:
      - ./.env
    expose:
      - 5000

  db:
    image: postgres:14.0-alpine
    volumes:
    - weather_database:/var/lib/postgresql/data/
    env_file:
    - ./.env

  web:
    image: avnosov/weather-web:v1
    volumes:
    - static_volume:/app/static/
    depends_on:
    - db
    env_file:
    - ./.env

  adminer:
    image: adminer:4.8.1-standalone
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
    depends_on:
      - web
      - adminer

volumes:
  static_volume:
  weather_database:
