# Generated by Django 2.2.19 on 2023-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_count', models.IntegerField(null=True, verbose_name='Количество запросов')),
                ('popular_commands', models.TextField(null=True, verbose_name='Наиболее популярные команды')),
            ],
            options={
                'verbose_name': 'Статистика из телеграмма',
                'verbose_name_plural': 'Статистика из телеграмма',
            },
        ),
        migrations.CreateModel(
            name='CommandStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=50, verbose_name='Название команды')),
                ('call_count', models.PositiveIntegerField(default=0, verbose_name='Количество вызовов')),
                ('date', models.DateTimeField(verbose_name='Дата статистики')),
            ],
            options={
                'verbose_name': 'Статистика команды',
                'verbose_name_plural': 'Статистика команд',
            },
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, verbose_name='Имя пользователя')),
                ('message', models.TextField(verbose_name='Сообщение пользователя')),
                ('date', models.DateTimeField(verbose_name='Дата отправки сообщения')),
                ('chat', models.CharField(max_length=256, null=True, verbose_name='Чат в котором отправили запрос')),
            ],
            options={
                'verbose_name': 'Информация из телеграмма',
                'verbose_name_plural': 'Информация из телеграмма',
                'ordering': ('-date',),
            },
        ),
    ]
