# Generated by Django 2.2.19 on 2023-07-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandstatistics',
            name='date',
        ),
    ]
